### ISSUE TITLE
Add ability to set default dependencies 

### ISSUE THREAD

**Issue by bono007** [spring-io/initializr#1027]
Many of the basic capabilities can currently be configured with [default](https://docs.spring.io/initializr/docs/current-SNAPSHOT/reference/html/#create-instance-basic-settings) values. These result in these values to be pre-selected in the UI as well as used on API requests.

It would be really nice to be able to specify the same on dependencies so that some dependencies could be pre-selected in the UI as well.

We have a custom fork of `start.spring.io` and we have to modify [index.js](https://github.com/spring-io/start.spring.io/blob/master/start-client/src/pages/index.js) pretty heavily to make this happen. 

I envision this in the yaml (the addition being the `default: true` at the bottom.

```
initializr:
 dependencies:
    - name: AcmeCompany
      content:
        - name: ACME Spring Boot Starter
           id: acme-spring-boot-starter
           groupId: com.acme
           artifactId: acme-spring-boot-starter
           scope: compile
           description: Acme Spring Boot Starter
           starter: true
           default: true
```
