### ISSUE TITLE
Make sample data a little nicer for local testing

### ISSUE THREAD

**Issue by dsyer** [spring-io/initializr#1455]
The sample has an `application.yml` that can't be used to test all the endpoints. E.g. you can build it locally and that works, but you can't curl `/pom.xm`l (400). A few lines of `application.yml` fixes that. I found this useful for testing locally (adding another dependency and project types to support the `/pom.xml` and `/build.gradle` endpoints:

```yaml
initializr:
  group-id:
    value: org.acme
  dependencies:
    - name: Web
      content:
        - name: Web
          id: web
          description: Servlet web application with Spring MVC and Tomcat
    - name: Spring Data JPA
      content:
        - id: data-jpa
          description: Persist data in SQL stores with Java Persistence API using Spring Data and Hibernate.
          facets:
            - jpa
          aliases:
            - jpa
          links:
            - rel: guide
              href: https://spring.io/guides/gs/accessing-data-jpa/
              description: Accessing Data with JPA
            - rel: reference
              href: https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsinge/index.html#data.sql.jpa-and-spring-data
  languages:
    - name: Java
      id: java
      default: true
    - name: Kotlin
      id: kotlin
      default: false
    - name: Groovy
      id: groovy
      default: false
  javaVersions:
    - id: 17
      default: true
    - id: 11
      name: 11
      default: false
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Maven Build
      id: maven-build
      description: Generate a Maven build configuration
      tags:
        build: maven
        format: build
      default: false
      action: /pom.xml
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
    - name: Gradle Build
      id: gradle-build
      description: Generate a Gradle build configuration
      tags:
        build: gradle
        format: build
      default: false
      action: /build.gradle
```
