### ISSUE TITLE
distributionManagement support

### ISSUE THREAD

**Issue by tokuhirom** [spring-io/initializr#300]
I want to inject distributionManagement on self-hosted initializr.

I want to configure it like following:

```
initializr:
  env:
    distributionManagement:
      - id: mavenrepository.googlecode.com
        url: scm:svn:https://mavenrepository.googlecode.com/svn/trunk
```
