### ISSUE TITLE
Define version ranges for dependencies

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#62]
With the release of Spring Boot 1.2.0, there are a set of new starters that are being made available but they are not defined yet. The main reason behind that is that if the user selects such starter and then choose Spring Boot 1.1.x the build will fail since that stater does not exist in that version.

This is a general issue (Spring Boot being the primary consumer in the case of `start.spring.io`). 

The purpose of this issue is to add an optional `versionRange` attribute to each dependency that would expose which versions apply for that dependency, something like:

```

initializr:
  dependencies:
    - name: Group
      content:
        - name: Foo
          id: foo
          versionRanges:
            - springBoot:
                from: 1.2.0.RELEASE
       - name: Bar
          id: bar
          versionRanges:
            - springBoot:
                from: 1.0.2.RELEASE
                to: 1.2.0.M1
```

That information would be exposed in the meta-data (v2.1 coming?) so that the client can use that information to react accordingly. In the case of the web UI, some javascript hook should enable/disable the visibility of the starter according to the Spring boot version chosen by the user.
