### ISSUE TITLE
Upgrade to Keycloak 4.2.0.Final

### ISSUE THREAD

**Issue by sebastienblanc** [spring-io/initializr#684]
Keycloak 4.0.0.Final has been released and there also a starter available for Spring Boot 2. I can provide a PR if needed , what I did locally in the application.yml : 
``` 
 mappings:
            - versionRange: 2.0.0.RELEASE
              groupId: org.keycloak
              artifactId: keycloak-spring-boot-2-starter
            - versionRange: "[1.5.3.RELEASE,2.0.0.M1)"
              groupId: org.keycloak
              artifactId: keycloak-spring-boot-starter  
``` 

And the new Keycloak version is updated in the bom section of the yaml file.
