### ISSUE TITLE
Define BOM per dependency

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#99]
Spring Initializr can be used to define starters or main dependencies on other projects that have their own dependency management. We could add such starter with a version but it would be much nicer to bring the _Bill Of Materials_ of that project along so that only one extra version is defined. Like that, additional dependencies are available in the project and their versioning is managed consistently.

The environment may define an arbitrary number of _bom_ entry. Each dependency may be associated to a bom via its chosen id. 

Example:

```yml
  env:
    boms:
      - id: bar
        groupId: org.foo
        artifactId: bar
        version: 1.2.3
        property: bar.version
```

If a dependency has a reference to `bar`, then a new entry in the dependency management of the project will be added and a new property will be extracted (`bar.version`) for easier overriding.
